apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-important-app
  namespace: application-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-important-app
  template:
    metadata:
      labels:
        app: super-important-app
    spec:
      containers:
        - name: super-important-app
          image: dockerlogtestservice
          imagePullPolicy: Never          
---
apiVersion: v1
kind: Service
metadata:
  name: super-important-app
  namespace: application-world
  labels:
    app: super-important-app
    spring-boot: "true"
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: super-important-app