apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: administration-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        imagePullPolicy: Never
        image: admin-server
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: admin
  namespace: administration-world
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: administration-world
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30181